# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=200)),
                ('link_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_text', models.CharField(max_length=200)),
                ('video_text', models.CharField(max_length=200)),
                ('audio_text', models.CharField(max_length=200)),
                ('subs_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('summary_text', models.CharField(max_length=200)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('runtime_minutes', models.IntegerField()),
                ('cover_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_text', models.CharField(max_length=200)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.Release')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('avatar_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.User'),
        ),
        migrations.AddField(
            model_name='release',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.Title'),
        ),
        migrations.AddField(
            model_name='release',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.User'),
        ),
        migrations.AddField(
            model_name='link',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.Upload'),
        ),
    ]
