# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20160923_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=200)),
                ('link_text', models.CharField(max_length=200)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.Upload')),
            ],
        ),
    ]
