# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20160923_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
