# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20160923_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
