# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_upload_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='summary_text',
            field=models.CharField(max_length=2000),
        ),
    ]
