# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20161005_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Upload'),
        ),
    ]
