# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_auto_20161005_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_url',
            field=models.CharField(max_length=2000),
        ),
    ]
