# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_auto_20161005_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
    ]
