# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_release_host_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='host_list',
        ),
        migrations.AddField(
            model_name='upload',
            name='host_list',
            field=models.CharField(default='', max_length=200),
        ),
    ]
