# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0018_title_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('image', models.CharField(default='default.png', max_length=100)),
            ],
        ),
    ]
