# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0019_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
