# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0020_auto_20161014_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.Host'),
        ),
    ]
