# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0021_auto_20161014_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.Host')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Upload')),
            ],
        ),
    ]
