# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0023_auto_20161014_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_name',
            new_name='hostname',
        ),
    ]
